[project]
name = "zrc-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ncatbot>=4.4.1.post1",
    "sqlalchemy>=2.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.1",
]
